### ISSUE TITLE
preparations for js-ipfs 0.35

### ISSUE THREAD

**Issue by dirkmc** [peer-base/peer-base#271]
👋 I upgraded ipfs to v0.35.0-rc.4 and ran the tests but there were some failures.

It looks like these are mostly caused by [ipfs._libp2pNode being moved to ipfs.libp2p](https://github.com/peer-base/peer-base/issues/239). It seems like there is a fix on this peer-base branch: https://github.com/peer-base/peer-base/pull/250, but when I checked it out and rebased to master there were still a few errors.

Here is the output of running the tests against master with ipfs v0.35.0-rc.4:
```
> peer-base@0.12.0-rc6 test:browser /Users/dirk/dev/ipfs/peer-base
> aegir test -t browser

Test Browser
rendezvous: Listening on: http://0.0.0.0:9090


ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.
  vectorclock
    doesRemoteNeedUpdate
      ✓ empty (1ms)
      ✓ local empty remote has changes
      ✓ remote empty local has changes
      ✓ local same as remote
      ✓ local lower value than remote
      ✓ local higher value than remote
      ✓ local some lower some higher than remote
    doesSecondHaveFirst
      ✓ empty
      ✓ first empty second full
      ✓ second empty first full
      ✓ first same as second
      ✓ first lower value than second
      ✓ first some lower some higher than second
    increment
      ✓ empty (6ms)
      ✓ undefined
      ✓ null
      ✓ with no author has no effect
      ✓ empty with author (1ms)
      ✓ with author not in clock
      ✓ with author
    isDeltaInteresting
      ✓ accepts one up
      ✓ does not accept already included
      ✓ accepts many up
      ✓ does not accept already included
      ✓ accepts concurrent that starts from inside
      ✓ does not accept concurrent that starts from outside
      ✓ does not accept concurrent whose only change is target peer id
      ✓ accepts concurrent that starts from inside and expands multiple
      ✓ does not accept concurrent that starts from inside and ends in self
      ✓ does not accept previous clock that is outside current clock
    isIdentical
      ✓ empty clocks
      ✓ clocks with single equal k/v
      ✓ clocks with multiple equal k/v
      ✓ empty vs single k/v
      ✓ single k/v vs empty
      ✓ same key but different value
      ✓ first subset of second
      ✓ second subset of first
    areDeltasJoint
      ✓ works
    diff
      ✓ two empties
      ✓ one empty one full
      ✓ one full one empty
      ✓ two distinct
      ✓ two intersecting (1ms)
    merge
      ✓ two empties
      ✓ one empty one full
      ✓ one full one empty
      ✓ two distinct
      ✓ two intersecting
    minimum
      ✓ two empties
      ✓ one empty one full
      ✓ one full one empty
      ✓ two distinct
      ✓ two intersecting
    subtract
      ✓ two empties
      ✓ one empty one full
      ✓ one full one empty
      ✓ two distinct
      ✓ two intersecting
    sumAll
      ✓ two empties
      ✓ one empty one full
      ✓ one full one empty
      ✓ two distinct
      ✓ two intersecting

  ring
    ✓ can be created
    ✓ can add a node (1ms)
    ✓ can get successor
    ✓ can add a few more nodes
    ✓ can get the successor
    ✓ can get the successor's successor
    ✓ can get the successor of the last
    ✓ can get the exact point at
    ✓ can get the point at
    ✓ can get the point at past end
    ✓ can get a point before start
    ✓ can remove a point

  dias set
    ✓ can be created (2ms)
    ✓ is empty at start
    ✓ can add a node (1ms)
    ✓ can add some nodes before 1/5th
    ✓ can add a node before 1/5th
    ✓ can add a node before 1/4th
    ✓ can add a node before 1/3rd
    ✓ can add a node after 1/2 (1ms)
    ✓ can work with poorly distributed small sets

  dias set inbound connections
    ✓ distributes inbound connections evenly (49ms)

  keys
    ✓ can be generated (32ms)
    ✓ can be uri-encoded (1ms)
    ✓ can be uri-decoded (1ms)
    ✓ can generate a new symmetrical key (4ms)

  app-transport
    ✓ can be created (2ms)
    ✓ can create a listener
    filtered discovery
      ✓ unconnected peer is filtered (102ms)
      ✓ uninteresting peer is filtered (105ms)
      ✓ interesting peer is discovered (5ms)

  membership
    unit
      ✓ sends single gossip message on start even if multiple gossip now events are fired during start (17ms)
      ✓ needs urgent broadcast on delivery of gossip summary message that doesnt match local hash (2ms)
      ✓ does not need urgent broadcast on delivery of gossip summary message that matches local hash (3ms)
      ✓ still needs urgent broadcast on delivery of hash mismatch followed by hash match (2ms)
      ✓ needs urgent broadcast on delivery of gossip message that doesnt contain this peer (4ms)
      ✓ needs urgent broadcast on delivery of gossip message that contains this peer but has the wrong addresses (3ms)
      ✓ does not need urgent broadcast on delivery of gossip message that does contain this peer and addresses (3ms)
      ✓ calculates matching hashes regardless of order of peers and addresses (8ms)
      ✓ has correct peer count and events when delivering remote membership (11ms)
    convergence
      ✓ has all members (1ms)
      ✓ knows all members addresses (6ms)

  dial tracker
    ✓ silently ignores removeDial for unknown dial id
    ✓ silently ignores cancel on peer that has not been dialed (1ms)
    ✓ before any dials should return false for dial accessors (1ms)
    ✓ should report dial to peer
    ✓ should handle multiple dials to multiple peers (1ms)
    ✓ should handle cancel of multiple dials (1ms)

  membership gossip frequency heuristic
    ✓ heuristic fires gossip now after each snapshot interval (189ms)
    ✓ heuristic fires event when a gossip message with a state change is received (22ms)
    ✓ heuristic does not fire event when a gossip message with no state change is received (66ms)
    ✓ heuristic does not fire event when a gossip message with a state change is received but peer count too high (62ms)
    ✓ heuristic does not fire events before starting (52ms)
    ✓ heuristic does not fire events until another peer is discovered (163ms)
    ✓ heuristic does not fire events after stopping (78ms)

  handling data
    ✓ correctly decodes data
    ✓ sets error argument if the data is incorrectly encoded (1ms)
    ✓ sets error argument if the handler function throws an error

  dial cache
    ✓ returns correct value on add (103ms)
    ✓ does not exceed capacity (1ms)
    ✓ add is fresh after remove

  dial throttle
    ✓ returns a valid value with default options (1ms)
    ✓ returns values in expected range (11ms)

  dialer
    ✓ returns correct backoff values (1ms)
    ✓ dial before start returns error
    ✓ backs off when there are dial errors (453ms)
    ✓ dials that do not complete within dialerMaxAttempts should return from callback with completed false and an error (106ms)
    ✓ fails after one dial when retry is false (11ms)
    ✓ dials interrupted by stop should return from callback with completed false (105ms)
    ✓ dials after stop should be ignored (52ms)
    ✓ cancelled dials should return from callback with completed false (63ms)
    ✓ cancelled retry dials should return from callback with completed false (56ms)

  discovery
    ✓ dials peers even if discovered before startup (164ms)
    ✓ dials peers discovered after startup (54ms)
    ✓ does not redial peer when dial is in progress (52ms)
    ✓ does not redial peer that is already connected (107ms)
    ✓ does not dial peer if discovery is interrupted by stop (53ms)
    ✓ repeatedly dials peer after connection error (108ms)
    ✓ allows redial immediately after unexpected disconnect (116ms)
    ✓ emits events for interested / not interested peers (14ms)

  peer interest discovery
    ✓ emits event showing interest in topic (6ms)
    ✓ does not hang up after event showing interest in topic (6ms)
    ✓ hangs up after event showing not interested in topic (5ms)
    ✓ times out after waiting for interest event (115ms)
    ✓ aborts timer immediately if the peer is disconnected (13ms)
    ✓ aborts timers immediately if interest discovery is stopped (18ms)

  connection manager
    ✓ connects to newly interested peers (53ms)
    ✓ disconnects from no longer interested peers (52ms)
    ✓ ignores interested peers that are already in ring and not interested peers that were not in ring (52ms)
    ✓ removes unexpectedly disconnected peer from ring (111ms)
    ✓ removes peer from ring if we receive a dial failure event (104ms)
    ✓ removes peer from ring if we dial and theres a failure (162ms)
    ✓ cleans up all connections on stop (52ms)

  app swarm
    1) "before all" hook
    2) "after all" hook

  app
    3) "before all" hook
    ✓ can be created

  peer count guess
    ✓ can be created
    ✓ can be started (8ms)
    4) gets some gossip
    ✓ can be stopped (1ms)

  collaboration
    5) "before all" hook
    6) "after all" hook

  collaboration gossip
    7) "before all" hook
    8) "after all" hook

  sub-collaboration
    9) "before all" hook
    10) "after all" hook

  public collaboration
    11) "before all" hook
    12) "after all" hook

  collaboration with random changes
    13) "before all" hook
    14) "after all" hook

  stats
    15) "before all" hook
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)
HeadlessChrome 73.0.3683 (Mac OS X 10.13.6) ERROR: 'error stopping IPFS:', Error: Not able to stop from state: starting
Error: Not able to stop from state: starting
    at Function.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:163396:23)
    at http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331911:14
    at new Promise (<anonymous>)
    at IPFS.<anonymous> (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:331906:12)
    at App.stop (http://localhost:9876/base/node_modules/aegir/src/config/karma-entry.js?16d14f8712a4d2375e025968968e5dd93ec55514:404033:25)


  161 passing (28s)
  15 failing

  1) app swarm
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  2) app swarm
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  3) app
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  4) peer count guess
       gets some gossip:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  5) collaboration
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  6) collaboration
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  7) collaboration gossip
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  8) collaboration gossip
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  9) sub-collaboration
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  10) sub-collaboration
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  11) public collaboration
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  12) public collaboration
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  13) collaboration with random changes
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  14) collaboration with random changes
       "after all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  

  15) stats
       "before all" hook:
     Error: Uncaught TypeError: Cannot read property '_floodSub' of undefined (/Users/dirk/dev/ipfs/peer-base/src/discovery/peer-interest-discovery.js:32:4 <- node_modules/aegir/src/config/karma-entry.js:408004)

  



Command failed: karma start /Users/dirk/dev/ipfs/peer-base/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
Error: Command failed: karma start /Users/dirk/dev/ipfs/peer-base/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
    at makeError (/Users/dirk/dev/ipfs/peer-base/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/dirk/dev/ipfs/peer-base/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peer-base@0.12.0-rc6 test:browser: `aegir test -t browser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the peer-base@0.12.0-rc6 test:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dirk/.npm/_logs/2019-03-29T14_13_28_886Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jimpick** [comment]
Thanks for looking at this! I knew it was likely to break ... it's good to see where now.

**Comment by dirkmc** [comment]
No worries, should be a fairly straightforward fix, the complicating factor is that a bunch of the tests simulate parts of the libp2p stack by creating a fake ipfs object, so those will probably need to be modified.
